version: "2.1"
services:
    mongodb:
        image: mongo:3.2.11
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo-client
            MONGO_INITDB_ROOT_PASSWORD: mongo-password
        volumes: 
          - ~/.pocket/mongodb:/data/db
        ports:
          - "27017:27017"
        networks:
          - pocket
    redis:
        image: "redis:alpine"
        command: redis-server
        ports:
          - "6379:6379"
        volumes:
          - ~/.pocket/redis:/var/lib/redis
          - ./redis.conf:/usr/local/etc/redis/redis.conf
        environment:
          - REDIS_REPLICATION_MODE=master
        networks:
          - pocket
networks:
    pocket:
        driver: bridge
